pipeline:
    name: test
    identifier: test
    projectIdentifier: harnessgosdk
    orgIdentifier: Micahs_Projects
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: org.githubharnessio
                repoName: harness-go-sdk
                build: <+input>
    stages:
        - stage:
              name: test
              identifier: test
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test
                                identifier: test
                                spec:
                                    connectorRef: org.gcp
                                    image: busybox:latest
                                    command: ls -la
                                    privileged: false
                  serviceDependencies: []
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.micahsprojects
                          namespace: micahs-projects
